### ISSUE TITLE
V2 Development

### ISSUE THREAD

**Issue by asmyshlyaev177** [asmyshlyaev177/react-horizontal-scrolling-menu#137]
In this [branch](https://github.com/asmyshlyaev177/react-horizontal-scrolling-menu/tree/v2) working on rewriting this library from scratch.

## Motivation
- It's overcomplicated now, too hard to maintain, e.g. getBoundingClientRect require computations, browser inconsistencies etc
- Too many options and callbacks
- Tracking visibility of items manually is too hard and leads to many bugs
- Can't implement swipe gestures on Touchpad/touchscreen

## Plan
- Use native browser scroll functionality
- Use [`IntersectionObserver`](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) for detect items visibility.
- Keep only basic functionality and add possibility to extend it.
- Use React Hooks

## TODO
- [x] PoC
- [x] Linting
- [x] Babel 
- [x] Browserslist config
- [x] Unit tests
- [x] E2E tests (better with SSR/TS, chrome/ff)
- [x] Types: TS or generate types from jsdoc 
- [x] React example
- [x] Example with SSR, e.g. NextJS
- [x] Custom classNames for wrapper and item
- [x] Example how to disable scroll on document.body
- [x] Github action workflow for tests 
- [x] Github pages example and deploy script
- [x] Collect some feedback
- [x] Cleanup and check everything
- [x] Fix github pages, it gives me 404 for all nextJS resources, set basePath and assetPrefix
- [x] Update gif in README

## HOWTO
Can install via `npm`
Current beta version `npm install — save react-horizontal-scrolling-menu@2.0.0-beta.8`

OR

- Clone repo and checkout `v2` branch
- `yarn install` in root dir and `yarn demo`
- Play around with it and say what you think about it in this thread

**Comment by harikautilya** [comment]
@asmyshlyaev177 let me know if i can help you achieve this. We have implemented this in our official website and it is causing problem. Hoping to solve the issues with new structure you are planning

**Comment by asmyshlyaev177** [comment]
> @asmyshlyaev177 let me know if i can help you achieve this. We have implemented this in our official website and it is causing problem. Hoping to solve the issues with new structure you are planning

You can try this version and see is it work correctly and if you need more features.

**Comment by sujishpatel** [comment]
I don't know what your goals are in terms of dependencies. But I recommend taking a look at [https://github.com/pmndrs/react-use-gesture](react-use-gesture) to help with the scrolling gestures. It works really well with [https://github.com/pmndrs/react-use-spring](react-spring) which could solve the animation aspect. 

I believe it should bundle up into a small package.

**Comment by asmyshlyaev177** [comment]
> I don't know what your goals are in terms of dependencies. But I recommend taking a look at [react-use-gesture](https://github.com/pmndrs/react-use-gesture) to help with the scrolling gestures. It works really well with [react-spring](https://github.com/pmndrs/react-use-spring) which could solve the animation aspect.
> 
> I believe it should bundle up into a small package.

With native browser scroll touchpad gestures just works natively, not sure if animation so important.

**Comment by asmyshlyaev177** [comment]
Published beta version `react-horizontal-scrolling-menu@2.0.0-beta.1`

**Comment by asmyshlyaev177** [comment]
Published beta version react-horizontal-scrolling-menu@2.0.0-beta.2

**Comment by asmyshlyaev177** [comment]
Published ` react-horizontal-scrolling-menu@2.0.0-beta.3` with TS support, will appreciate if somebody can help replace `any`

**Comment by joelrojo** [comment]
@asmyshlyaev177 Really awesome rewrite!

I'm finding that whenever I trigger `scrollNext` or `scrollPrev`, it causes the page to scroll vertically to the `ScrollMenu` element itself. Our horizontal menu is not at the top of the page, and we hope to use this in many places in our app, but the vertical auto scroll (caused by `scrollIntoView` being called by `scrollToItem`) is something we'd like to avoid.

Here is what the issue looks like:

![Kapture 2021-06-23 at 16 28 58](https://user-images.githubusercontent.com/217719/123180480-352bf200-d440-11eb-932e-ca1de8f85dc7.gif)

Any ideas on how to solve this or remove the vertical scroll?

Another small but nice addition would be a className prop on `ScrollMenu` that allows us to add custom class names to the `.react-horizontal-scrolling-menu--wrapper` div.

Thanks for building this!

**Comment by asmyshlyaev177** [comment]
> @asmyshlyaev177 Really awesome rewrite!
> 
> I'm finding that whenever I trigger `scrollNext` or `scrollPrev`, it causes the page to scroll vertically to the `ScrollMenu` element itself. Our horizontal menu is not at the top of the page, and we hope to use this in many places in our app, but the vertical auto scroll (caused by `scrollIntoView` being called by `scrollToItem`) is something we'd like to avoid.
> 
> Here is what the issue looks like:
> 
> ![Kapture 2021-06-23 at 16 28 58](https://user-images.githubusercontent.com/217719/123180480-352bf200-d440-11eb-932e-ca1de8f85dc7.gif)
> 
> Any ideas on how to solve this or remove the vertical scroll?
> 
> Another small but nice addition would be a className prop on `ScrollMenu` and on the that allows us to add custom class names to the `.react-horizontal-scrolling-menu--wrapper` div and also on the items themselves to add classes to `.react-horizontal-scrolling-menu--item`
> 
> Thanks for building this!

Thanks for participating.

Published `beta.4`
Added options with default values to scroll functions, seems like `block: 'nearest'` in [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) fixed the issue, can you check again?

Will add css classNames a little later.

**Comment by joelrojo** [comment]
Thanks for the quick update @asmyshlyaev177 

Just tried to update to `beta.4` and `beta.5` and am now getting this issue:

```
Failed to execute 'scrollIntoView' on 'Element': The provided value '[object Object]' is not a valid enum value of type ScrollBehavior.
```

<img width="608" alt="Screen Shot 2021-06-28 at 9 05 31 PM" src="https://user-images.githubusercontent.com/217719/123735748-9d217480-d854-11eb-9ff8-7784b40f4c39.png">

Wondering if it might be something with the way I configured it?

**Comment by asmyshlyaev177** [comment]
@joelrojo better to see how you use it. Somewhere passed object as argument.

**Comment by asmyshlyaev177** [comment]
`react-horizontal-scrolling-menu@2.0.0-beta.7` with example how to use drag by mouse.

**Comment by asmyshlyaev177** [comment]
Published version `2.0.0`
